# Generated by Django 4.0.3 on 2022-03-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('short_id', models.SlugField(max_length=6, primary_key=True, serialize=False, verbose_name='Сокращенная ссылка')),
                ('httpurl', models.URLField(verbose_name='Полная ссылка')),
                ('pup_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания ссылки')),
                ('count', models.IntegerField(default=0, verbose_name='Количество переходов по ссылке')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
