# Generated by Django 4.0.3 on 2022-03-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenersite', '0002_alter_urls_httpurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.RenameField(
            model_name='urls',
            old_name='pup_date',
            new_name='pub_date',
        ),
    ]
