# Generated by Django 4.0.3 on 2022-03-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenersite', '0003_alter_urls_options_rename_pup_date_urls_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='short_id',
            new_name='slug',
        ),
    ]
