# Generated by Django 4.0.3 on 2022-03-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenersite', '0004_rename_short_id_urls_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='httpurl',
            new_name='full_url',
        ),
    ]
