# Generated by Django 4.0.3 on 2022-03-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenersite', '0005_rename_httpurl_urls_full_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urls',
            old_name='count',
            new_name='count_clicks',
        ),
    ]
