# Generated by Django 4.0.3 on 2022-03-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenersite', '0006_rename_count_urls_count_clicks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urls',
            options={'ordering': ('-creation_date',), 'verbose_name': 'Ссылка', 'verbose_name_plural': 'Ссылки'},
        ),
        migrations.RenameField(
            model_name='urls',
            old_name='pub_date',
            new_name='creation_date',
        ),
    ]
