# Generated by Django 4.0.3 on 2022-03-29 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortenersite', '0007_alter_urls_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls',
            new_name='Url',
        ),
    ]
